### PR TITLE
Support for MIDI models in HARP.

### PR DESCRIPTION
**Pull request by cwitkowitz**
Introduces basic support and display for Midi-to-Midi models along with a major cleanup of the underlying GUI components that control media display.

### CODE REVIEW

**Comment by cwitkowitz** [comment]
This should now be good to go. We just need to make sure we update the commit and branch for the pyharp submodule after https://github.com/TEAMuP-dev/pyharp/pull/15 is merged, and that we update the compatibility table in the README.

**Comment by cwitkowitz** [comment]
@xribene, @NathanPruyne, this branch has been rebased to the current `main` and can be merged if it all looks good to you guys. I also moved the undo/redo stuff to the `MediaDisplayComponent` class to decouple it from the model.

**Comment by NathanPruyne** [comment]
I'm currently having a failed build on Windows with:
```
C:\HARP\HARP\src\media\AudioDisplayComponent.h(100,1): error C4716: 'AudioDisplayComponent::getPlaybackPosition': must
return a value [C:\HARP\HARP\build-win\HARP.vcxproj]
```

Seems like the value isn't actually returned there explicitly (i.e. with "return"). I'll try to debug this and then pr a branch into this one, and also make sure it works on Linux with the fix.

**Comment by NathanPruyne** [comment]
Ok, that fix seems to have worked, and is in #192 . I think this is good to go!

Couple notes for improving the MIDI display in the future:

- Upon file load we might want to jump the display down to where there's actual MIDI content so it's clear that it's loaded. It might not hurt to jump there for after processing too to clearly display the new content.
- IMHO actual note names (e.g. "B3", "C4", "C#4", etc.) would be more useful for the y-axis labels than the MIDI note numbers.
- Horizontal scroll should probably be limited to the length of the MIDI file. Maybe limit vertical scroll to the highest and lowest notes of the file too?

**Review by xribene — APPROVED** [review]

**Comment by cwitkowitz** [comment]
Nice catch @NathanPruyne. In terms of your comments on the MIDI display, I'm actually working on this right now in a separate branch (`fc/pianoroll_improvements`). I'm pretty much in agreement with what you're suggesting.

**Pull request merged**
